spring:
  application:
    name: E-commerce API Gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
  cloud:
    gateway:
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL}
          predicates:
            - Path=/auth/**

        - id: customer-service
          uri: ${CUSTOMER_SERVICE_URL}
          predicates:
            - Path=/api/v1/customers/**,/api/v1/addresses/**

        - id: product-service
          uri: ${PRODUCT_SERVICE_URL}
          predicates:
            - Path=/api/v1/products/**,/api/v1/categories/**

        - id: cart-service
          uri: ${CART_SERVICE_URL}
          predicates:
            - Path=/api/v1/cart/**

        - id: order-service
          uri: ${ORDER_SERVICE_URL}
          predicates:
            - Path=/api/v1/orders/**

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

info:
  app:
    name: api-gateway
    version: 1.0.0

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8484
