spring:
  application:
    name: Cart Service
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI}
          audiences: cart-service

services:
  product:
    url: ${PRODUCT_SERVICE_URL}
  order:
    url: ${ORDER_SERVICE_URL}

keycloak:
  token-url: ${KEYCLOAK_TOKEN_URL}
  client-id: cart-service
  client-secret: ${CLIENT_SECRET}

logging:
  level:
    org.springframework.security: DEBUG

server:
  port: 8282
